body:
  - type: input
    attributes:
      name: chatUrl
      label: Chat URL
      description: Make sure to include the prompt parameter in the URL. For example, https://chatgpt.com/?prompt=
      defaultValue: "https://chatgpt.com/?prompt="
